version: 2.1
#
# SPDX-FileCopyrightText: Copyright (c) 2025 Robert Di Pardo
# SPDX-License-Identifier: GPL-3.0-or-later
#
orbs:
  lazarus: rdipardo/lazarus@4
  win: circleci/windows@5

references:
  executor: &executor
    executor:
      name: win/default
  development: &development
    filters:
      tags:
        only: /v.*/
  production: &production
    context: gh-release-authoring
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /v.*/

parameters:
  plugin_name:
    type: string
    default: PreviewHTML

jobs:
  build:
    <<: *executor
    steps:
      - checkout
      - run:
          name: Clone submodules
          command: |
            git submodule sync --recursive
            git submodule update --init --recursive
      - lazarus/install:
          win32: true
      - run:
         name: Build and Pack
         command: .\lazarus\make_release.cmd
         shell: cmd.exe
      - unless:
          condition:
            matches:
              pattern: 'v.*'
              value:   << pipeline.git.tag >>
          steps:
            - run:
               name: Prepare Artifacts
               command: |
                 7z a -tzip << pipeline.parameters.plugin_name >>_x64.zip ./src/config/*.ini ./out/x86_64-win64/Release/*.dll
                 7z a -tzip << pipeline.parameters.plugin_name >>_win32.zip ./src/config/*.ini ./out/i386-win32/Release/*.dll
            - store_artifacts:
                name: Upload << pipeline.parameters.plugin_name >>_win32.zip
                path: << pipeline.parameters.plugin_name >>_win32.zip
                destination: << pipeline.parameters.plugin_name >>_win32.zip
            - store_artifacts:
                name: Upload << pipeline.parameters.plugin_name >>_x64.zip
                path: << pipeline.parameters.plugin_name >>_x64.zip
                destination: << pipeline.parameters.plugin_name >>_x64.zip
      - persist_to_workspace:
          root: .
          paths: out

  push_release:
    <<: *executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - store_artifacts:
          name: Upload << pipeline.parameters.plugin_name >>_<< pipeline.git.tag >>_win32.zip
          path: out/<< pipeline.parameters.plugin_name >>_<< pipeline.git.tag >>_win32.zip
          destination: << pipeline.parameters.plugin_name >>_<< pipeline.git.tag >>_win32.zip
      - store_artifacts:
          name: Upload << pipeline.parameters.plugin_name >>_<< pipeline.git.tag >>_x64.zip
          path: out/<< pipeline.parameters.plugin_name >>_<< pipeline.git.tag >>_x64.zip
          destination: << pipeline.parameters.plugin_name >>_<< pipeline.git.tag >>_x64.zip
      - run:
          name: Create GitHub Release
          command: bash.exe .circleci/scripts/gh_release.sh
          shell: bash.exe
          environment:
            SLUGX86: << pipeline.parameters.plugin_name >>_<< pipeline.git.tag >>_win32.zip
            SLUGX64: << pipeline.parameters.plugin_name >>_<< pipeline.git.tag >>_x64.zip
            BIN_DIR: out

workflows:
  lazarus_build:
    jobs:
      - build:
          <<: *development
      - push_release:
          <<: *production
          requires:
            - build

