;; Visit https://github.com/rdipardo/npp_preview/wiki/Settings to learn more.
;;;;;;;;;;;;;;;;;;
; Global Options ;
;;;;;;;;;;;;;;;;;;
; [Emulation]
; NoEdge=1

; [AutoRefresh]
; Interval=2000

;;;;;;;;;;;;;;;;;;;;
; WebView2 Options ;
;;;;;;;;;;;;;;;;;;;;
; [Scroll]
; Sticky=0

; [Style]
; Disable=0
; Filename=custom_style.css
; Extension=.md,.adoc

; [JavaScript]
; Disable=0
; Filename=custom_script.js
; Extension=.php

; [Katex]
;; https://katex.org/docs/browser
; Version=0.17
; AutoRender=0

; [MathJax]
;; https://docs.mathjax.org/en/latest/web/start.html
; Version=3
; Components=es5/tex-svg

; [JQuery]
; Version=3.7.1
